### ISSUE TITLE
关于vs压制报错的问题

### ISSUE THREAD

**Issue by hnwangji** [zyzsdy/NegativeEncoder#21]
在压制中加载字幕会提示以下报错
D:\qitdown\1_nevs_batTemp.bat 
Script evaluation failed:
Python exception: No attribute with the name vsf exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "D:\qitdown\1_nevs_vpyTemp.vpy", line 11, in <module>
    video = core.vsf.TextSub(video, SUB_PATH.encode('gbk'))
  File "src\cython\vapoursynth.pyx", line 1660, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1522, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name vsf exists. Did you mistype a plugin namespace?

y4m: failed to parse y4m header.
failed to initialize file reader(s).
Failed to open input file.
找不到批处理文件。

这个错误会在你压制中止后再次压制时弹出报错，这在0.4.1版本也出现了，清理缓存，重装都没用，请问有什么解决方法？

**Comment by zyzsdy** [comment]
删掉代码生成器自动添加上的 `.encode('gbk')` 部分。
下一版本的vs代码生成器将更新自带python运行环境，并且停止自动添加该代码段落。

**Comment by hnwangji** [comment]
按照您提供的方法删除后还是报错，只不过getattr后面多了一个“_”
D:\qitdown\1_nevs_batTemp.bat 
Script evaluation failed:
Python exception: No attribute with the name vsf exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "D:\qitdown\1_nevs_vpyTemp.vpy", line 11, in <module>
    video = core.vsf.TextSub(video, SUB_PATH)
  File "src\cython\vapoursynth.pyx", line 1660, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1522, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name vsf exists. Did you mistype a plugin namespace?

y4m: failed to parse y4m header.
failed to initialize file reader(s).
Failed to open input file.
找不到批处理文件。

**Comment by zyzsdy** [comment]
不好意思，没有仔细看你的报错，以为是一个我们已知的常见问题了。

你这个问题是vs滤镜没有正确加载的原因造成的。但是NegativeEncoder自带了所有的加载滤镜。
具体到你这个问题缺少的是VSFilter.dll

在开始压制后会调用安装目录下的\Libs\VapourSynth.dll，VapourSynth.dll会在vapoursynth64\plugins目录下尝试加载所有的滤镜。

如果你在NegativeEncoder之外单独安装了VapourSynth的话，或者系统环境变量中存在相关的设置，可能导致VapourSynth.dll的自动搜索路径发生改变。你应该尝试检查是否有自己安装过VS，并保证系统的滤镜库中也有VSFilter.dll（你可以简单的把NegativeEncoder安装目录\Libs\vapoursynth64\plugins\VSFilter.dll复制过去使用）

如果不是以上原因造成，请提供给我更多的可能信息以便我们分析问题。
